# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html

python:
   version: 3.11

conda:
  environment: docs/environment.yml