name: enveloc
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.2
  - pip=23.2.1
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.1
  - xz=5.2.6
  - pip:
      - appnope==0.1.3
      - asttokens==2.2.1
      - backcall==0.2.0
      - bleach==6.0.0
      - build==0.10.0
      - cartopy==0.22.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.0
      - decorator==5.1.1
      - docutils==0.20.1
      - enveloc==1.1.4
      - executing==1.2.0
      - fonttools==4.42.0
      - greenlet==2.0.2
      - idna==3.4
      - importlib-metadata==6.8.0
      - ipython==8.14.0
      - jaraco-classes==3.3.0
      - jedi==0.19.0
      - joblib==1.3.2
      - keyring==24.2.0
      - kiwisolver==1.4.4
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - numpy==1.25.2
      - obspy==1.4.0
      - packaging==23.1
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - pkginfo==1.9.6
      - prompt-toolkit==3.0.39
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pyparsing==3.0.9
      - pyproj==3.6.0
      - pyproject-hooks==1.0.0
      - pyshp==2.3.1
      - python-dateutil==2.8.2
      - readme-renderer==40.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.5.2
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - shapely==2.0.1
      - six==1.16.0
      - sqlalchemy==2.0.19
      - stack-data==0.6.2
      - threadpoolctl==3.2.0
      - traitlets==5.9.0
      - twine==4.0.2
      - typing-extensions==4.7.1
      - urllib3==2.0.4
      - utm==0.7.0
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - zipp==3.16.2
